config/routes.rb
Rails.application.routes.draw do


  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendship, only: [:create, :destroy]
  resources :users, only: [:show], :constraints => { :id => /[0-9|]+/ }
  post 'friendship/:id' => 'friendship#create', as: :create_friendship


 get 'search_friends', to: 'users#search_friend', as: 'search_friends'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    query = BasicYahooFinance::Query.new
    data = query.quotes(ticker_symbol, 'price')

    if data.key?(ticker_symbol) && data[ticker_symbol].key?('regularMarketPrice')
      price_raw = data[ticker_symbol]['regularMarketPrice']['raw']

      stock = find_by_ticker(ticker_symbol)
      if stock
        stock.update(last_price: price_raw)
      else
        stock = create(ticker: ticker_symbol, last_price: price_raw)
      end

      stock
    else
      # Return nil if the data doesn't have the expected structure
      nil
    end
  end

  def price_formatted
    # Assuming you have a column in the Stock model called `last_price`
    # This method should return the formatted price information
    return '$' + last_price.to_s if last_price.present?

    # If no price information is available, return 'N/A' or any other suitable value
    'N/A'
  end

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker)
    stock = Stock.find_by_ticker(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
    end


  def under_stock_limit?
    stocks.count<10
  end

  def can_track_stock?(ticker)
    under_stock_limit? && !stock_already_tracked?(ticker)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Annonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end

  def friends_with?(id_of_friend)
    self.friends.where(id: id_of_friend).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :fetch_tracked_stocks, if: :user_signed_in?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  private

  def fetch_tracked_stocks
    @tracked_stocks = current_user.stocks
  end
end

app/controllers/friendship_controller.rb
class FriendshipController < ApplicationController


  def destroy
    friendship = current_user.friendships.find_by(friend_id: params[:id])
    friendship.destroy!
    flash[:notice] = "Stopped following"
    redirect_to my_friends_path
  end

  def create
    friend = User.find(params[:id])
    friendship = current_user.friendships.build(friend_id: friend.id)

    if friendship.save
        flash[:notice] = "Following user"
      else
        flash[:alert] = "There was something wrong with tracking request"
      end
      redirect_to my_friends_path

  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
     @user = current_user
    if params[:stock].present?
     @stock = Stock.new_lookup(params[:stock])
     if @stock
      render 'users/my_portfolio'
     else
      flash[:alert] = "Please enter a valid symbol to search"
      redirect_to my_portfolio_path
     end
   else
     flash[:alert]="Please enter a symbol to search"
     redirect_to my_portfolio_path
   end
 end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock_info = Stock.new_lookup(params[:ticker])
     if stock_info
        stock = Stock.find_by_ticker(stock_info[:ticker])
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added yo your portfolio"
        redirect_to my_portfolio_path
        return
        else
        flash[:alert] = "Unable to find stock with ticker #{params[:ticker]}"
      end
   redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker.upcase} was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    
    @tracked_stocks = current_user.stocks
    @tracked_stocks = [] if @tracked_stocks.nil?  # Ensure it's an empty array if nil
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
  if params[:friend].present?
    friend_name = params[:friend].downcase
    @friends = User.search(friend_name)
    @friends = current_user.except_current_user(@friends)
    if @friends.any?
      render 'friends/search_result', friends: @friends
    else
      flash[:alert] = "No friend found with the provided name"
      redirect_to my_friends_path
    end
  else
    flash[:alert] = "Please enter a friend's name to search"
    redirect_to my_friends_path
  end
end

def my_friends
  @tracked_friends = current_user.friends || []
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
  <div class="row">
    <div class="col-9">
      <% if @tracked_friends.present? %>
        <table class="table table-bordered table-hover mt-3">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Email</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @tracked_friends.each_with_index do |friend, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= friend.first_name %></td>
                <td><%= friend.last_name %></td>
                <td><%= friend.email %></td>
                <td>

              <%= link_to link_to 'Unfollow', friendship_path(friend), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                          class: 'btn btn-sm btn-warning' %>
                          <%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success mr-4" %>
            </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        No tracked friends found.
      <% end %>
    </div>
  </div>

app/views/friends/search_result.html.erb
<h1>My Friends</h1>

<div class='search-area'>
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Email or name", autofocus: true, class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 na-left-padding">
        <%= button_tag type: :sumbit, class: "btn btn-success" do %>
        <%= content_tag :i, '', class: 'fa fa-search fa-2x' %>
        <% end %>
      </div>
    </div>
 <% end %>
</div>

<%= render 'users/friend_result' %>

<div>
<%= link_to 'Back to My Friends', my_friends_path, class: 'btn btn-sm btn-light' %>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">

        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger alert-dismissible fade show '>
        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
          
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
<%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
<% if current_user %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= "active" if request.path == my_portfolio_path %>">
        <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Friends', my_friends_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu">
          <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <%= content_tag(:i, "", class: "fa fa-edit") %>
              Edit profile
            <% end %>
             <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
  </div>


  <ul class="navbar-nav custom-mr-5">
    <li class="nav-item user-name">
    <i class="fa fa-user"></i>  <%= current_user.full_name %>
    </li>
    <li class="nav-item">
      <%= link_to("Logout", destroy_user_session_path, class: "btn btn-xs btn-outline-danger", data: { "turbo-method": :delete }) %>
    </li>
  </ul>


    <form class="d-flex justify-content-end" role="search">
       <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
       <button class="btn btn-outline-success" type="submit">Search</button>
     </form>

  <% end %>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-cache-control" content="no-cache">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'custom' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<% if @stock %>
  <% if current_user.can_track_stock?(@stock.ticker) %>
  <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock[:ticker]), class: "btn btn-xs btn-success ml-3", data: { "turbo-method": :post,turbo: true, local: true } %>
  <% else %>
   <span class="badge badge-secondary">
     You are already tracking
    </span>
  <% end %>
<% end %>

<div class="row">
  <div class="col-9">
    <% if @tracked_stocks.present? %>
      <table class="table table-bordered table-hover mt-3">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Ticker</th>
            <th scope="col">Price</th>
            <th scope="col class="action-column">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each_with_index do |stock, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td><%= stock.ticker.upcase %></td>
              <td><%= stock.price_formatted %></td>
              <td><% if current_user.can_track_stock?(stock.ticker) %>
              <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock[:ticker]), class: "btn btn-xs btn-success ml-3", data: { "turbo-method": :post,turbo: true, local: true } %>
              <% elsif current_user.id != @user.id %>
               <span class="badge badge-secondary">
                 You are already tracking
                </span>
              <% end %>

                <% if current_user.id == @user.id %>
                <%= link_to 'Remove', user_stock_path(stock), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'},
                class: 'btn btn-sm btn-warning' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      No tracked stocks found.
    <% end %>
  </div>
</div>

app/views/users/_friend_result.html.erb
  <% if @friends %>
    <div class="card card-header results-block mt-2">
      <table class="col-md-12">
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <td><strong>Name: </strong> <%= friend.full_name %> | </td>
              <td><strong>Email: </strong> <%= friend.email %> | </td>
              <td><strong>Actions  :</strong><%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success mr-4" %></td>

              <td>

                <% if current_user.not_friends_with?(friend.id) %>
                  <%= link_to 'Follow friend?', friendship_path(friend), data: {turbo_method: :post, turbo_confirm: 'Are you sure?' },
                  class: "btn btn-sm btn-success" %>

                  <% else %>
                  <span class="badge badge-secondary bg-dark-text">
                    You are friends
                   </span>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>

app/views/users/_result.html.erb
<turbo-frame id="stock-info">
  <% if @stock %>
    <div class="card card-header results-block">
       <strong>Symbol: </strong> <%= @stock[:ticker].upcase %>
       <strong>Price: </strong> <%= @stock[:last_price] %>$
       <% if current_user.can_track_stock?(@stock.ticker) %>
       <% else %>
        <span class="badge bg-dark">
          You are already tracking
          <% if !current_user.under_stock_limit? %>
          10 stocks
          <% end %>
          <%if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
          <% end %>
        </span>
       <% end %>
    </div>
 <% end %>
</turbo-frame>

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class='search-area'>
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Email or name", autofocus: true, class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 na-left-padding">
        <%= button_tag type: :sumbit, class: "btn btn-success" do %>
        <%= content_tag :i, '', class: 'fa fa-search fa-2x' %>
        <% end %>
      </div>
    </div>
 <% end %>
</div>

<% if @tracked_friends.present? %>
<%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='search-area'>
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 na-left-padding">
        <%= button_tag type: :sumbit, class: "btn btn-success" do %>
        <%= content_tag :i, '', class: 'fa fa-search fa-2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'users/result' %>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
    <div class="card card-header results-block mt-2">
      <table class="col-md-12">
        <tbody>
            <tr>
              <td><strong>Name: </strong> <%= @user.full_name %> | </td>
              <td><strong>Email: </strong> <%= @user.email %> | </td>
            </tr>
        </tbody>
      </table>
    </div>


<%= render 'stocks/list' %>




<div>
<%= link_to 'Back to My Friends', my_friends_path, class: 'btn btn-sm btn-light' %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to My Finance Tracker App</h1>
<p>Go to My Portfolio to add some stocks or try My Friends to search for your friends.</p>